
set(THIRDLIBS_BUILD_TYPE "")
if(CMAKE_BUILD_TYPE STREQUAL "Debug")
	MESSAGE(STATUS "Building project in debug mode ...")
    set(THIRDLIBS_BUILD_TYPE "debug")
	set(MS_PATH_SUFFIX_86 "lib/Debug/x86")
	set(MS_PATH_SUFFIX_64 "lib/Debug/x64")
	set(UNIX_PATH_SUFFIX_86 "bin/Debug/x86")
	set(UNIX_PATH_SUFFIX_64 "bin/Debug/x64")
elseif(CMAKE_BUILD_TYPE STREQUAL "Release")
	MESSAGE(STATUS "Building project in release mode ...")
    set(THIRDLIBS_BUILD_TYPE "release")
	set(MS_PATH_SUFFIX_86 "lib/Release/x86")
	set(MS_PATH_SUFFIX_64 "lib/Release/x64")
	set(UNIX_PATH_SUFFIX_86 "bin/Release/x86")
	set(UNIX_PATH_SUFFIX_64 "bin/Release/x64")
else()
    MESSAGE( STATUS "CMAKE_BUILD_TYPE not set yet ${CMAKE_BUILD_TYPE}" )
	set(MS_PATH_SUFFIX_86 "lib/Release/x86")
	set(MS_PATH_SUFFIX_64 "lib/Release/x64")
	set(UNIX_PATH_SUFFIX_86 "bin/Release/x86")
	set(UNIX_PATH_SUFFIX_64 "bin/Release/x64")
endif()

option(BUILD_SHARED_LIBS "Build external shared/static libraries" OFF)
#If these options are turned off, the targetted dependencies won't be downloaded. However, they are mandatory requirement for this project.
#So please make sure that the dependencies can be found by a find_package call in config mode before turning the options off.
option(GLM_AUTO_DOWNLOAD "Download glm dependency via FetchContent_MakeAvailable" ON)
option(GLEW_AUTO_DOWNLOAD "Download glew dependency via FetchContent_MakeAvailable" ON)
option(WXWIDGETS_AUTO_DOWNLOAD "Download wxWidgets dependency via FetchContent_MakeAvailable" ON)
option(OPENAL_AUTO_DOWNLOAD "Download OpenAL dependency via FetchContent_MakeAvailable" ON)